version: '3.8'
services:
  auth:
    build:
      context: .
      args:
        - APP=auth
    restart: always
    environment:
      - HTTP_PORT=3000
      - TCP_PORT=53000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth?schema=public
      - JWT_SECRET=eed1ce4063da37344c988c6c174a99ef6a804f0833855384d3738014d7c53296
      - JWT_EXPIRATION=3600
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - SENTRY_DSN=
    command: sh -cx "npx prisma db push && node dist/apps/auth/main"
    ports:
      - 3000:3000
      - 53000:53000
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
        
  products:
    build:
      context: .
      args:
        - APP=products
    restart: always
    environment:
      - HTTP_PORT=3001
      - TCP_PORT=53001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/products?schema=public
      - AUTH_HOST=auth
      - AUTH_PORT=53000
      - SHOPIFY_HOST=shopify
      - SHOPIFY_PORT=53003
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - SENTRY_DSN=
    command: sh -cx "npx prisma db push && node dist/apps/products/main"
    ports:
      - 3001:3001
      - 53001:53001
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  orders:
    build:
      context: .
      args:
        - APP=orders
    restart: always
    environment:
      - HTTP_PORT=3002
      - TCP_PORT=53002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/orders?schema=public
      - AUTH_HOST=auth
      - AUTH_PORT=53000
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - SENTRY_DSN=
    command: sh -cx "npx prisma db push && node dist/apps/orders/main"
    ports:
      - 3002:3002
      - 53002:53002
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  shopify:
    build:
      context: .
      dockerfile: ./apps/shopify/Dockerfile
    restart: always
    environment:
      - HTTP_PORT=3003
      - TCP_PORT=53003
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - SHOPIFY_STORE_URL=${SHOPIFY_STORE_URL}
      - SHOPIFY_API_VERSION="2024-01"
      - ORDERS_HOST=orders
      - ORDERS_PORT=53002
      - RABBITMQ_URI=amqp://rabbitmq:5672
    ports:
      - 3003:3003
      - 53003:53003
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    build: ./rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5672:5672
      - 15672:15672

